require("./styles/styles.scss");
require("./styles/components.scss");

const { cx, Locale } = require("@bsi-cx/design-build");

module.exports = cx.design
  .withTitle("Trangourmet BSI CX")
  .withAuthor("gateB")
  .withDate("08.11.2022")
  .withDefaultLocale(Locale.DE)
  .withLocales(Locale.DE)
  .withContentElementGroups(
    cx.contentElementGroup
      .withGroupId("landingpage-header")
      .withLabel("Header")
      .withContentElements(
        require("./content-elements/landingpage-header/bild-fixe-breite-responsive"),
        require("./content-elements/landingpage-header/bild-ganze-breite"),
        require("./content-elements/landingpage-header/farbleiste-fixe-breite"),
        require("./content-elements/landingpage-header/farbleiste-ganze-breite"),
        require("./content-elements/landingpage-header/logo"),
        require("./content-elements/landingpage-header/navigation")
      ),
    cx.contentElementGroup
      .withGroupId("headings")
      .withLabel("Überschriften")
      .withContentElements(
        require("./content-elements/headings/ueberschrift-h1"),
        require("./content-elements/headings/ueberschrift-h2"),
        require("./content-elements/headings/ueberschrift-h3")
      ),
    cx.contentElementGroup
      .withGroupId("forms")
      .withLabel("Formulare")
      .withContentElements(
        require("./content-elements/forms/form-checkbox"),
        require("./content-elements/forms/form-field"),
        require("./content-elements/forms/form-field-date"),
        require("./content-elements/forms/form-field-horizontal"),
        require("./content-elements/forms/form-file-input"),
        require("./content-elements/forms/form-radio"),
        require("./content-elements/forms/form-radio-nps-numeric"),
        require("./content-elements/forms/form-radio-nps-string"),
        require("./content-elements/forms/form-radio-smiley"),
        require("./content-elements/forms/form-radio-star-numeric"),
        require("./content-elements/forms/form-radio-star-string"),
        require("./content-elements/forms/form-select"),
        require("./content-elements/forms/form-select-enhanced"),
        require("./content-elements/forms/form-slider-group"),
        require("./content-elements/forms/form-slider-group-header"),
        require("./content-elements/forms/form-slider-group-slider"),
        require("./content-elements/forms/form-tel-input"),
        require("./content-elements/forms/form-text"),
        require("./content-elements/forms/form-textarea"),
        require("./content-elements/forms/hidden-input"),
        require("./content-elements/forms/single-column-form-slim"),
        require("./content-elements/forms/single-column-form-wide"),
        require("./content-elements/forms/two-column-form"),
        require("./content-elements/forms/two-column-form-complex")
      ),
    cx.contentElementGroup
      .withGroupId("texts-images")
      .withLabel("Texte & Bilder")
      .withContentElements(
        require("./content-elements/texts-images/abstand"),
        require("./content-elements/texts-images/button"),
        require("./content-elements/texts-images/button-fullwidth"),
        require("./content-elements/texts-images/hervorgehobener-inhalt-primary"),
        require("./content-elements/texts-images/hervorgehobener-inhalt-secondary"),
        require("./content-elements/texts-images/image"),
        require("./content-elements/texts-images/image-no-legend"),
        require("./content-elements/texts-images/image-swipe-links"),
        require("./content-elements/texts-images/image-title-cta"),
        require("./content-elements/texts-images/qr-code"),
        require("./content-elements/texts-images/tabelle"),
        require("./content-elements/texts-images/text"),
        require("./content-elements/texts-images/text-rich"),
        require("./content-elements/texts-images/trenner")
      ),
    cx.contentElementGroup
      .withGroupId("footer")
      .withLabel("Footer Elemente")
      .withContentElements(
        require("./content-elements/footer/footer-company"),
        require("./content-elements/footer/footer-social"),
        require("./content-elements/footer/footer-spalten-1"),
        require("./content-elements/footer/footer-spalten-2"),
        require("./content-elements/footer/footer-spalten-3"),
        require("./content-elements/footer/footer-spalten-4")
      ),
    cx.contentElementGroup
      .withGroupId("columns")
      .withLabel("Spalten")
      .withContentElements(
        require("./content-elements/columns/content-column-slim"),
        require("./content-elements/columns/spalten-2"),
        require("./content-elements/columns/spalten-3"),
        require("./content-elements/columns/spalten-4")
      ),
    cx.contentElementGroup
      .withGroupId("special")
      .withLabel("Diverses")
      .withContentElements(
        require("./content-elements/special/google-maps"),
        require("./content-elements/special/news-snippets"),
        require("./content-elements/special/pie-chart"),
        require("./content-elements/special/pie-chart-without-table"),
        require("./content-elements/special/ugm-ranking"),
        require("./content-elements/special/video"),
        require("./content-elements/special/video-thumbnail"),
        require("./content-elements/special/webcam-image-upload"),
        require("./content-elements/special/widget-html"),
        require("./content-elements/special/cookie-banner")
      ),
    cx.contentElementGroup
      .withGroupId("script-elements")
      .withLabel("Script Elements")
      .withContentElements(
        require("./content-elements/script-elements/page-category-01"),
        require("./content-elements/script-elements/page-category-02"),
        require("./content-elements/script-elements/page-category-03"),
        require("./content-elements/script-elements/page-category-04"),
        require("./content-elements/script-elements/eventID"),
        require("./content-elements/script-elements/user-profile-profileInfo-loginStatus"),
        require("./content-elements/script-elements/user-profile-profileInfo-profileID")
      )
  );
